name: Deploy to DockerHub
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vue_heroku_node:latest

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Authenticate to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Link project
        run: railway link -p ${{ secrets.RAILWAY_PROJECT_ID }} -s ${{ secrets.RAILWAY_SERVICE_NAME }}

      - name: Deploy project
        run: railway up
